baseURL: /
title: "Sam Smith"

paginate: 10
disablePathToLower: true
languageCode: en-gb
theme: "anubis"

params:
  author: "Sam Smith"
  dark_css: "css/dark.css"

summaryLength: 999999999999

menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 0

    - identifier: archive
      name: Archive
      url: /posts/
      weight: 1

  footer:
    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 0

    - identifier: categories
      name: Categories
      title: Categories
      url: /categories/
      weight: 0

taxonomies:
  category: categories
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true
