baseURL: /
title: Sam Smith

paginate: 10
disablePathToLower: true
languageCode: en-gb
theme: "anubis"
summaryLength: 999999999999
googleAnalytics: UA-160189334-1

params:
  author: Sam Smith
  dark_css: "css/dark.css"

menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 0

    - identifier: archive
      name: Archive
      url: /posts/
      weight: 1

  footer:
    - identifier: categories
      name: Categories
      title: Categories
      url: /categories/
      weight: 0

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 1

taxonomies:
  category: categories
  tag: tags

markup:
  highlight:
    style: trac
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true
