name: github pages

on:
  push:
    branches:
      - source
  repository_dispatch:
    types: [scheduler]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.65.3'
          extended: true

      - name: Add scheduler
        run: |
          mkdir -p static/.github/workflows
          echo -e "name: scheduler\non:\n\tschedule:\n\t\t- cron: '*/" $(expr $(for d in $(cat content/post/* | awk '/date: / {gsub(/"/, "", $2); print $2 }'); do expr $(date -d $d +%s) - $(date +%s); done | awk '$1>=0' | sort -nk 1 | head -n 1) / 60 + 1) "* * * *'\n\njobs:\n\tdeploy:\n\t\truns-on: ubuntu-latest\n\t\tsteps:\n\t\t\t- uses: peter-evans/repository-dispatch@v1\n\t\t\t\twith:\n\t\t\t\t\ttoken: ${{ secrets.REPO_ACESS_TOKEN }}\n\t\t\t\t\trepository: sams96/sams96/github.io\n\t\t\t\t\tevent-type: scheduler" > static/.github/workflows/scheduler.yaml

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./public
